### ISSUE TITLE
Вопросы

### ISSUE THREAD

**Issue by ffnull** [microdimmer/homeweather_esp8266#2]
Здраствуйте! 
Напечатал все детали, собрал. Но
Ни в какую не работает подсветка по датчику. В дебаге постоянно 1024.
В вариации с TL431 в схеме, похоже что ошибка - не работает от слова совсем. Временно сделал просто через резистор 5кОм
Можно исходники корпуса? Так-как были другие кнопки и датчик CO2 и пришлось колхозить.
Кнопки дают мисклики.
И главное: Спасибо за шикарный проект!

**Comment by ffnull** [comment]
Еще вопрос о калибровке CO2. Возможно добавить параметр отключения автокалибровки и включение калибровки по 400ppm?

**Comment by ffnull** [comment]
Автор, вы жив?

**Comment by microdimmer** [comment]
Добавил 3d-модель в паку step. По второму вопросу - это для чего?

**Comment by microdimmer** [comment]
Странно, но не приходят уведомления на почту, только сейчас увидел.

**Comment by ffnull** [comment]
Спасибо за исходники. Пробую переписать под MQTT. Так-же добавил конденсатор на 1000Мфх16В в цепь 5В для стабилизации моргания подсветки во время включения нагрева датчика CO2. Единственное не знаю что делать с датчиком света, для автояркости. Ну и контрастность через TL431  у меня не заработала от слова совсем. Трижды перепроверил.

**Comment by microdimmer** [comment]
Если что можно списаться https://t.me/microdimmer
